/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school.course.mangment.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Gui_Start extends javax.swing.JFrame {
  public ArrayList <Student> s = new ArrayList(); 
public ArrayList <Teacher> t = new ArrayList(); 
public ArrayList <Admin> admin = new ArrayList(); 
public ArrayList <IT> it = new ArrayList(); 
public ArrayList <Accountant> a = new ArrayList(); 
public ArrayList <Program> p = new ArrayList(); 

    /**
     * Creates new form 
     */
    public Gui_Start() {
        initComponents();
        initObjects(); 
    }

     public void initObjects(){
          Module eng=new Module("english",22,2,"60%");
 

     Department admin = new Department(1,"Admin");
     Department IT = new Department(2,"IT");
     Department Teach = new Department(3,"Teaching");
     Department Account = new Department(4,"Accounting");
     
     Accountant K=new Accountant(1000,2012,Account,"KAREEM210520","GZ6FY","KAREEM","28/9","kareeem@bue","012278"); 
     Accountant z=new Accountant(1050,2014,Account,"mohamed870","GZhyY","mohamed","18/9","mohamed@bue","01004875"); 
this.a.add(K);
this.a.add(z);
     Teacher teacher1=new Teacher("doctor",15,9,115,eng,5000,2018,Teach,"mariam876","7654","mariam","4/4","mariam@bue","0125478");
     Teacher teacher2=new Teacher("doctor",16,8,116,eng,5000,2019,Teach,"nour564","5663","nour","8/4","nour@bue","0123374");
this.t.add(teacher1);
this.t.add(teacher2);

     IT it1=new IT(3200,2006,IT,"tamer7865","jhiufhf","tamer","18/7","tamer@bue","01427856");
     IT it2=new IT(3800,2009,IT,"ibrahim9087","dfgfn","ibrahim","18/5","ibrahim@bue","0328181");
this.it.add(it1);
this.it.add(it2);
     Program ig = new Program("IGCSE", 40,6,3.5);
     Program n = new Program("National", 50,8,3);
     Program a = new Program("American", 40,4,2.5);
this.p.add(ig);
this.p.add(n);
this.p.add(a);
     Classroom H = new Classroom('H',20); 
     Classroom A = new Classroom('A',25); 

     Admin admin1 = new Admin(5000,2012,admin,"admin_Ahmed","admin1234","Ahmed","1960","@@","0124"); 
     Admin sup = new Admin(5000,2002,admin,"admin","bue","Mohammed","1960","@@","0124"); 

     Admin admin2 = new Admin(5000,2012,admin,"admin_Hussin","admin1234","Ahmed","1960","@@","0124"); 
this.admin.add(admin1);
this.admin.add(admin2);
this.admin.add(sup);
     Student one = new Student(2018,"022245", 45648,"IGCSE",'H',3.2,ig,H,"noeman1","1234","Noeman","2002","@@","01115946"); 
     Student two = new Student(2018,"022245", 45648,"IGCSE",'H',3.2,ig,H,"ahmed","1234","Ahmed","2002","@@","01115946"); 
     Student three = new Student(2018,"022245", 45648,"IGCSE",'H',3.2,ig,H,"eso","1234","islam","2002","@@","01115946"); 
     Student four = new Student(2018,"022245", 45648,"IGCSE",'H',3.2,ig,H,"m_s","1234","mohamed","2002","@@","01115946"); 
this.s.add(one);
this.s.add(two);
this.s.add(three);
this.s.add(four);
     }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Student = new javax.swing.JRadioButton();
        Teacher = new javax.swing.JRadioButton();
        Admin = new javax.swing.JRadioButton();
        Accountant = new javax.swing.JRadioButton();
        IT = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/book.png"))); // NOI18N
        jLabel1.setText("International School Informatin System");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 130, -1));

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 176, -1));
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 176, -1));

        buttonGroup1.add(Student);
        Student.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Student.setForeground(new java.awt.Color(255, 255, 255));
        Student.setText("Student");
        jPanel1.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, -1, -1));

        buttonGroup1.add(Teacher);
        Teacher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Teacher.setForeground(new java.awt.Color(255, 255, 255));
        Teacher.setText("Teacher");
        jPanel1.add(Teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        buttonGroup1.add(Admin);
        Admin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("Admin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jPanel1.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, -1, -1));

        buttonGroup1.add(Accountant);
        Accountant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Accountant.setForeground(new java.awt.Color(255, 255, 255));
        Accountant.setText("Accountant");
        jPanel1.add(Accountant, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, -1, -1));

        buttonGroup1.add(IT);
        IT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IT.setForeground(new java.awt.Color(255, 255, 255));
        IT.setText("IT technician");
        IT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITActionPerformed(evt);
            }
        });
        jPanel1.add(IT, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/import.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/laptop.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/mortarboard.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/apple-fruit.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/management.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/wallet.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/b.JPG"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/folder.png"))); // NOI18N
        jMenu1.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/course/mangment/system/close.png"))); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void ITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ITActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(Username.getText().isEmpty() || Password.getText().isEmpty()){JOptionPane.showMessageDialog(null, "Please fill all fileds");}
        else{
    
    String username = Username.getText();
    String password = Password.getText();
    boolean tr =false;
    Student.setActionCommand("s");
    Teacher.setActionCommand("t");
    Admin.setActionCommand("ad");
    Accountant.setActionCommand("a");
    IT.setActionCommand("i");
    String r = buttonGroup1.getSelection().getActionCommand();
    
    if(r=="s") {
       for(int i=0; i < this.s.size(); i++){
           if(this.s.get(i).getUsername().equals(username) ){
               if(s.get(i).verifyStudentLogin(username, password)!=null){ 
               Gui_Student screen = new Gui_Student(); 
               screen.catchObj(s.get(i));
               screen.welcome();
               screen.show(); 
               screen.sendProg(this.p); 
               this.dispose();
               tr = true; 
               break;
               }
           }
       else{

           }

       }
                        if(tr==false) 
                            JOptionPane.showMessageDialog(null, "Try again!");
    }
    else if(r=="t"){
        for(int i=0; i < this.t.size(); i++){
           if(this.t.get(i).getUsername().equals(username) ){
               if(t.get(i).verifyTeacherLogin(username, password)!=null){ 
               Gui_Teacher screen = new Gui_Teacher(); 
               screen.catchObj(t.get(i));
               screen.Welcome();
               screen.show(); 
               this.dispose();
               tr = true; 
               break;
               }
           }
       else{

           }

       }
                        if(tr==false) 
                            JOptionPane.showMessageDialog(null, "Try again!");
    
    }
    else if(r=="a"){
        for(int i=0; i < this.a.size(); i++){
           if(this.a.get(i).getUsername().equals(username) ){
               if(a.get(i).verifyACCOUNTANTLogin(username, password)!=null){ 
               Gui_Accountant screen = new Gui_Accountant(); 
               screen.catchObj(a.get(i));
               screen.Welcome();
               screen.show(); 
               this.dispose();
               tr = true; 
               break;
               }
           }
       else{

           }

       }
                        if(tr==false) 
                            JOptionPane.showMessageDialog(null, "Try again!");
    }
    else if(r=="ad"){
          for(int i=0; i < this.admin.size(); i++){
           if(this.admin.get(i).getUsername().equals(username) ){
               if(admin.get(i).verifyAdminLogin(username, password)!=null){ 
               Gui_Admin screen = new Gui_Admin(); 
               screen.catchObj(admin.get(i));
               screen.Welcome();
               screen.show(); 
               this.dispose();
               tr = true; 
               break;
               }
           }
       else{

           }

       }
                        if(tr==false) 
                            JOptionPane.showMessageDialog(null, "Try again!");
        
    }
    else if(r=="i"){new Gui_IT().setVisible(true);}
    
  }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Accountant;
    private javax.swing.JRadioButton Admin;
    private javax.swing.JRadioButton IT;
    private javax.swing.JPasswordField Password;
    private javax.swing.JRadioButton Student;
    private javax.swing.JRadioButton Teacher;
    private javax.swing.JTextField Username;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
